apiVersion: v1
kind: Pod
metadata:
  name: podnet-01
spec:
  containers:
   - name: web
     image: nginx
   - name: ubuntu
     image: ubuntu:16.04
     command: ["/bin/sh", "-c", "while : ;do curl http://localhost:80/; sleep 10; done"]