apiVersion: v1
entries:
  mysql:
  - apiVersion: v1
    appVersion: 5.7.14
    created: "2019-08-21T15:10:17+09:00"
    description: Fast, reliable, scalable, and easy to use open-source relational
      database system.
    digest: 60df04fdbc9a69fee4d000c62dccf185eb8fdf7cc4090cd49347f26e8e3763e1
    engine: gotpl
    home: https://www.mysql.com/
    icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
    keywords:
    - mysql
    - database
    - sql
    maintainers:
    - email: o.with@sportradar.com
      name: olemarkus
    - email: viglesias@google.com
      name: viglesiasce
    name: mysql
    sources:
    - https://github.com/kubernetes/charts
    - https://github.com/docker-library/mysql
    urls:
    - charts/mysql-0.1.0.tgz
    version: 0.1.0
generated: "2019-08-21T15:10:33+09:00"
serverInfo: {}
