apiVersion: v1
kind: Pod
metadata:
  name: skaffold
spec:
  containers:
  - name: skaffold
    image: gcr.io/k8s-skaffold/skaffold
    command: ["/bin/bash", "-c", "--" ]
    args: ["while true; do sleep 30; done;"]
